### Задание 1:
1. Привидите практические примеры всех унарных функций, перечисленных выше. В отдельной строке перед примером
необходимо дать описание каждой функции.
2. Привидите практические примеры всех бинарных функций, перечисленных выше. В отдельной строке перед
примером необходимо дать описание каждой функции.

#### Унарные:

In [9]:
import numpy as np
arr = np.arange(10)  # создание из диапазона
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)  # квадратный корень каждого элемента

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)  # экспонента каждого элемента

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### Бинарные

In [31]:
x = np.random.randn(8)  # созданем вектор из 8 элементов и наполняем случайными величинами из нормального распределения
y = np.random.randn(8)  # разница с rand https://stackoverflow.com/questions/57863277/when-to-use-numpy-random-randn-and-when-numpy-random-rand
x

array([ 0.31256995,  0.19101307, -0.15838189, -1.13438815,  0.66298377,
       -0.09481256, -1.53892828, -0.8809754 ])

In [32]:
y

array([-0.80503078,  0.60359228,  0.1263375 , -0.14369207,  0.0787453 ,
       -0.69283585, -0.10724935,  0.21880666])

In [28]:
np.random.rand(8, 4)

array([[0.53494005, 0.26957803, 0.95150326, 0.49375043],
       [0.15675673, 0.54610134, 0.96919054, 0.00354534],
       [0.19116382, 0.27401849, 0.10599784, 0.58762685],
       [0.33658238, 0.55882227, 0.71092379, 0.95518255],
       [0.55313585, 0.37756684, 0.02921892, 0.22177714],
       [0.8828187 , 0.69142111, 0.35823595, 0.7785218 ],
       [0.22933203, 0.37508376, 0.10909083, 0.92830773],
       [0.09743802, 0.16995025, 0.64327274, 0.62164849]])

In [33]:
np.maximum(x, y)  # применяем функцию max для каждого элемента между двумя матрицами

array([ 0.31256995,  0.60359228,  0.1263375 , -0.14369207,  0.66298377,
       -0.09481256, -0.10724935,  0.21880666])

In [38]:
arr = np.random.randn(7)
arr

array([-1.01040773, -0.2356623 ,  0.56804766,  0.90007373, -1.93411277,
        0.64866664, -1.52095024])

In [39]:
arr = arr * 5  # умножаем каждый элемент матрицы на 5
arr

array([-5.05203863, -1.1783115 ,  2.84023828,  4.50036865, -9.67056385,
        3.24333319, -7.60475121])

In [41]:
remainder, whole_part = np.modf(arr)
remainder, whole_part  # остатки и результат от деления

(array([-0.05203863, -0.1783115 ,  0.84023828,  0.50036865, -0.67056385,
         0.24333319, -0.60475121]),
 array([-5., -1.,  2.,  4., -9.,  3., -7.]))

### Программирование с применением массивов

In [42]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [46]:
# как не надо делать:
# 1. Для больших массивов - это не быстро.
# 2. К многомерным массивам такое решение неприменимо.
result = [
    (x if c else y) for x, y, c in zip(xarr, yarr, cond)
]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [48]:
# как надо:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [49]:
# Предположим, что имеется матрица со случайными данными и мы хотим заменить все положительные значения на 2, а все отрицательные значения на -2.
arr = np.random.randn(4, 4)
arr

array([[-0.66596644, -1.15668888, -0.90033648,  1.42644479],
       [ 0.31968797, -0.08826368, -0.81292469,  0.1843293 ],
       [ 1.0749629 ,  0.5405219 , -0.34512006, -1.53184229],
       [ 1.6194121 ,  0.02445805, -1.59663792, -2.06356102]])

In [50]:
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2, -2],
       [ 2,  2, -2, -2]])

In [51]:
np.where(arr > 0, 2, arr)

array([[-0.66596644, -1.15668888, -0.90033648,  2.        ],
       [ 2.        , -0.08826368, -0.81292469,  2.        ],
       [ 2.        ,  2.        , -0.34512006, -1.53184229],
       [ 2.        ,  2.        , -1.59663792, -2.06356102]])

### Математические и статистические операции

In [53]:
arr = np.random.randn(5, 4)
arr

array([[-0.63295174,  2.20748655, -0.20023746, -0.58656071],
       [-0.69636464, -0.03223784, -0.42050927, -0.62144715],
       [ 0.08240028,  0.89656553,  0.19341064,  1.26073292],
       [ 1.31034514,  0.33443099,  0.28361468,  1.93971317],
       [ 1.28012877, -0.47900137,  0.35264033, -0.69290896]])

In [54]:
arr.mean()

0.2889624936720311

In [56]:
np.mean(arr)

0.2889624936720311

In [57]:
arr.sum()

5.779249873440621

In [58]:
arr.mean(axis=1)

array([ 0.19693416, -0.44263972,  0.60827734,  0.967026  ,  0.11521469])

In [59]:
arr.sum(axis=0)

array([1.34355782, 2.92724386, 0.20891892, 1.29952927])

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [68]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
np.array([[1, 2], [3, 4], [5, 6]]).cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [71]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
# возвращает кумулятивную сумму для оси
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [73]:
# возвращает кумулятивное произведение для оси
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

In [75]:
# возвращает среднее для оси
arr.mean(axis=0)

array([4., 5., 6.])

In [76]:
# возвращает стандартное отклонение для оси
arr.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [80]:
# возвращает дисперсию для оси
arr.var(axis=0)

array([6., 6., 6.])

In [82]:
# возвращает минимальное значения для заданной оси
arr.min(axis=1)

array([1, 4, 7])

In [85]:
# возвращает индекс минимального значения для заданной оси
arr.argmin(axis=0)

array([0, 0, 0])

### Методы булевых массивов

In [87]:
arr = np.random.randn(100)
(arr > 0).sum() # количество положительных значений

48

In [88]:
# есть ли хоть одно верное
bools = np.array([False, False, True, False])
bools.any()

True

In [91]:
# все ли верные
bools.all()

False

### Сортировка

In [93]:
arr = np.random.randn(6)
arr

array([-0.38465704, -0.03349123, -0.78940012,  0.32847483, -1.0091193 ,
        0.74975863])

In [94]:
arr.sort()
arr

array([-1.0091193 , -0.78940012, -0.38465704, -0.03349123,  0.32847483,
        0.74975863])

In [95]:
arr = np.random.randn(5, 3)
arr

array([[-1.10641433, -0.31167532, -1.64495841],
       [ 0.44719327, -1.54461365,  0.53956624],
       [ 1.06193181, -0.80920296,  0.30611004],
       [ 0.64875499, -0.46829137, -0.4697883 ],
       [-1.12639208, -0.5987202 , -0.53419853]])

In [102]:
arr.sort(axis=1)
arr

array([[-1.64495841, -1.10641433, -0.31167532],
       [-1.54461365,  0.44719327,  0.53956624],
       [-0.80920296,  0.30611004,  1.06193181],
       [-0.4697883 , -0.46829137,  0.64875499],
       [-1.12639208, -0.5987202 , -0.53419853]])

In [107]:
# Метод верхнего уровня np.sort возвращает отсортированную копию массива, а не сортирует массив на месте.
# Например, чтобы вычислить квантили массива, необходимо отсортировать его и выбрать значение с конкретным рангом:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5%ый квантиль

-1.6665087962718463

### Удаление дубликатов и другие теоретико-множественные операции

In [108]:
# np.unique - возвращает отсортированное множество уникальных значений в массиве:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [109]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [110]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [111]:
np.intersect1d(values, [2, 3, 6])  # пересечение

array([2, 3, 6])

In [112]:
np.union1d(values, [2, 3, 6])  # объединение

array([0, 2, 3, 5, 6])

In [113]:
np.setdiff1d(values, [2, 3, 6])  # разница

array([0, 5])

In [122]:
np.setxor1d(values, [2, 3, 6])  # xor

array([0, 5])

In [130]:
np.setdiff1d([1, 2, 3], [4, 5, 6])

array([1, 2, 3])

In [129]:
np.setxor1d([1, 2, 3], [4, 5, 6])

array([1, 2, 3, 4, 5, 6])

### Файловый ввод-вывод массивов

In [132]:
arr = np.arange(10)
np.save('some_array', arr)

In [133]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.savez('array_archive.npz', a=arr, b=arr)

In [135]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

### Линейная алгебра

In [137]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [138]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [139]:
x.dot(y)  # Выражение X.dot(X) вычисляет произведение матрицы x на траспонированную к ней матрицу y.Т

array([[ 28.,  64.],
       [ 67., 181.]])

In [140]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [141]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [142]:
x @ np.ones(3)

array([ 6., 15.])

In [144]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)  # инверсия матрицы

array([[ 1.33559599, -0.40643779, -0.64625021,  0.41701106, -0.65561139],
       [-0.40643779,  1.42808546,  2.45820242, -0.85129357,  1.94882387],
       [-0.64625021,  2.45820242,  5.36055474, -1.58265589,  4.33729726],
       [ 0.41701106, -0.85129357, -1.58265589,  0.90219975, -1.34823174],
       [-0.65561139,  1.94882387,  4.33729726, -1.34823174,  3.67552439]])

In [145]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  8.54974664e-17,  1.02458645e-16,
         3.68455006e-17,  7.08277546e-18],
       [-1.09842898e-16,  1.00000000e+00,  2.43988383e-17,
         4.75124301e-16, -8.69194052e-16],
       [-1.30385233e-16,  2.73832703e-15,  1.00000000e+00,
        -3.02982540e-15,  7.52356645e-15],
       [-1.36787639e-16, -1.51332016e-16, -5.16126452e-16,
         1.00000000e+00, -1.97932932e-16],
       [-4.33381074e-16,  1.08347966e-15,  6.18262499e-16,
        -1.00761787e-15,  1.00000000e+00]])

In [146]:
mat

array([[ 0.95149588,  0.32354679, -0.70190722, -0.28940379,  0.72029796],
       [ 0.32354679,  4.24724842, -2.99407953,  1.3425614 ,  1.83137914],
       [-0.70190722, -2.99407953,  6.4823352 , -0.83051051, -6.49180295],
       [-0.28940379,  1.3425614 , -0.83051051,  3.04470946,  1.33341321],
       [ 0.72029796,  1.83137914, -6.49180295,  1.33341321,  7.57928022]])

In [150]:
q, r = qr(mat)
r

array([[-1.45095981, -3.24902133,  7.32085336, -0.56601195, -7.51777261],
       [ 0.        , -4.65924833,  4.62964843, -2.74419377, -4.01216388],
       [ 0.        ,  0.        , -4.39119237,  0.80543605,  5.64086156],
       [ 0.        ,  0.        ,  0.        , -2.26374107, -0.88318546],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.16144349]])

### Генерация псевдо-случайных чисел

In [ ]:
samples = np.random.randint(size=(4, 4))
samples

In [151]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

725 ms ± 102 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [152]:
%timeit np.random.normal(size=N)

26 ms ± 3.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
np.random.seed(1234)  # начальное значение на основе котором работает генератор псевдослучайных чисел

In [155]:
# Для генерации данных из модуля numpy,random используется глобальное начальное значение.
# Чтобы не вводить глобальное состояние, можно воспользоваться методом numpy.random.RandomState,
# который порождает случайное число, не зависящее от прочих.
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])