In [16]:
import array
L = list(range(5))
A = array.array('i', L)
L

[0, 1, 2, 3, 4]

In [18]:
A

array('i', [0, 1, 2, 3, 4])

In [14]:
import numpy as np
A = np.array([1, 0, -2, 4, 3])
B = np.array([0, 1, 2, 3], dtype='float32')
A

array([ 1,  0, -2,  4,  3])

In [20]:
B

array([0., 1., 2., 3.], dtype=float32)

In [26]:
B = np.array([range(i, i + 3) for i in [0, 2, 4]])
B

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [48]:
B = np.array([
    [1, 2.0],
    [0, 0],
    (1 + 1j, 3.)
])
B

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [50]:
np.array([
    [1, 2],
    [2, 3],
])

array([[1, 2],
       [2, 3]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [204]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [63]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [212]:
np.zeros(2)

array([0., 0.])

In [68]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
np.eye(5, k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [88]:
B = ([1,2,3], [4,5,6]) # В – массив-шаблон
np.zeros_like(B)

array([[0, 0, 0],
       [0, 0, 0]])

In [90]:
A = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
A

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [100]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
A[:2]

array([0, 1])

In [127]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [130]:
A = np.array([
    [1, 5, 3, 0],
    [7, 2, 8, 1],
    [1, 6, 3, 7],
])
B = A[:2, :3]
B

array([[1, 5, 3],
       [7, 2, 8]])

In [136]:
A[:, 3]

array([0, 1, 7])

In [149]:
a = np.array([0, -1, -2, -3])
b = np.arange(4)

print(a + b, a / b, a + 1, a < 0)

[0 0 0 0] [nan -1. -1. -1.] [ 1  0 -1 -2] [False  True  True  True]


/var/folders/xc/5y8sdzl55133mlz80hkp_0sh0000gn/T/ipykernel_76407/334266364.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(a + b, a / b, a + 1, a < 0)


In [175]:
print('matrix:  \n', A)
print('flat:  \n', np.ravel(A))
print('ndarray.flatten: \n', np.ndarray.flatten(A))
print('transpose:  \n', np.transpose(A))
print('A.T:  \n', A.T)
print('swapaxes: \n', np.swapaxes(A, axis1=0, axis2=1))

matrix:  
 [[1 5 3 0]
 [7 2 8 1]
 [1 6 3 7]]
flat:  
 [1 5 3 0 7 2 8 1 1 6 3 7]
ndarray.flatten: 
 [1 5 3 0 7 2 8 1 1 6 3 7]
transpose:  
 [[1 7 1]
 [5 2 6]
 [3 8 3]
 [0 1 7]]
A.T:  
 [[1 7 1]
 [5 2 6]
 [3 8 3]
 [0 1 7]]
swapaxes: 
 [[1 7 1]
 [5 2 6]
 [3 8 3]
 [0 1 7]]


In [466]:
A = np.array([[1, 2, 3], [11, 12, 13]])
B = np.empty_like(A)
A

array([[ 1,  2,  3],
       [11, 12, 13]])

In [467]:
B

array([[4594091047235908320, 4599874317905123802, 4605930610539430349],
       [4603623567549445930, 4607021558116234636, 4602905579630007618]])

In [473]:
np.copyto(B, A)
B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [474]:
np.ravel(A)

array([ 1,  2,  3, 11, 12, 13])

In [498]:
A.reshape(-1)

array([ 1,  2,  3, 11, 12, 13])

In [499]:
A.reshape(3, 2)

array([[ 1,  2],
       [ 3, 11],
       [12, 13]])

In [502]:
A.reshape(1, 6)

array([[ 1,  2,  3, 11, 12, 13]])

In [504]:
A = np.arange(6).reshape((2, 3))
A

array([[0, 1, 2],
       [3, 4, 5]])

In [505]:
np.transpose(A)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [506]:
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [510]:
A = np.ones((2, 3, 4))  # вектор из двух элементов-матриц размером 3 строки и 4 столбца
A
# [
#     [
#         [1., 1., 1., 1.],
#         [1., 1., 1., 1.],
#         [1., 1., 1., 1.]
#     ],
#     [
#         [1., 1., 1., 1.],
#         [1., 1., 1., 1.],
#         [1., 1., 1., 1.]
#     ]
# ]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [513]:
A.shape

(2, 3, 4)

In [519]:
B = np.moveaxis(A, -1, 0)
B.shape

(4, 2, 3)

In [520]:
B  # вектор из 4-х элементов-матриц состоящих из 2-х строк и 3-х столбцов

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [521]:
A = [1, 2]
B = np.asarray(A)
A is B

False

In [523]:
a = np.array([1, 2])
np.asarray(a) is a

True

In [525]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0, 1] = 8

In [529]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 11]])
c = np.concatenate((a, b), axis=0)
c

array([[ 1,  2],
       [ 3,  4],
       [10, 11]])

In [541]:
np.concatenate((a, ([6], [8])), axis=1)

array([[1, 2, 6],
       [3, 4, 8]])

In [538]:
np.concatenate((a, ([6, 7, 77], [8, 9, 99])), axis=1)

array([[ 1,  2,  6,  7, 77],
       [ 3,  4,  8,  9, 99]])

In [542]:
np.concatenate((a, b.T), axis=1)

array([[ 1,  2, 10],
       [ 3,  4, 11]])

In [549]:
np.concatenate((a, np.array([[6, 7]]).T), axis=1)

array([[1, 2, 6],
       [3, 4, 7]])

In [550]:
np.concatenate((a, b), axis=None)

array([ 1,  2,  3,  4, 10, 11])

In [553]:
x = np.arange(12.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [554]:
np.split(x, 3)

[array([0., 1., 2., 3.]), array([4., 5., 6., 7.]), array([ 8.,  9., 10., 11.])]

In [557]:
np.split(x, [2, 5, 7])

[array([0., 1.]),
 array([2., 3., 4.]),
 array([5., 6.]),
 array([ 7.,  8.,  9., 10., 11.])]

In [558]:
a = np.array([0, 1, 2])
np.tile(a, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [562]:
b = np.array([[1, 2], [3, 4]])
c = np.tile(b, 2)
c

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [563]:
a = np.repeat(2, 3)
a

array([2, 2, 2])

In [567]:
c = np.repeat(b, 3, axis=1)
c

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [569]:
c = np.repeat(b, 3, axis=0)
c

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [572]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.delete(a, 1, 0)
b

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [573]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.insert(a, 1, 0)
b

array([1, 0, 2, 3, 4, 5, 6])

In [574]:
c = np.insert(a, 1, 7, axis=1)
c

array([[1, 7, 2],
       [3, 7, 4],
       [5, 7, 6]])

In [575]:
a = [1, 2, 3]
d = np.append(a, [[4, 5, 6], [7, 8, 9]])
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [577]:
a = np.array([[1, 2], [3, 4], [5, 6]])
e = np.append(a, [[7, 8]], axis=0)
e

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [580]:
a = np.array([[0, 1], [10, 11]])
c = np.resize(a, (2, 4))
c

array([[ 0,  1, 10, 11],
       [ 0,  1, 10, 11]])

In [585]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [586]:
b = np.flip(a, 0)
b

array([[4, 5],
       [2, 3],
       [0, 1]])

In [587]:
b = np.flip(a, 1)
b

array([[1, 0],
       [3, 2],
       [5, 4]])

In [589]:
a = np.arange(10)
b = np.roll(a, 2)
b

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [590]:
b = np.reshape(a, (2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [591]:
c = np.roll(b, 1)
c

array([[9, 0, 1, 2, 3],
       [4, 5, 6, 7, 8]])

In [593]:
c = np.roll(b, 1, axis=0)
c

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [595]:
c = np.roll(b, 2, axis=1)
c

array([[3, 4, 0, 1, 2],
       [8, 9, 5, 6, 7]])

In [596]:
a = np.array([[0, 1], [1, 7]])
b = np.unique(a)
b

array([0, 1, 7])

In [598]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
b = np.unique(a, axis=0)
b

array([[1, 0, 0],
       [2, 3, 4]])

In [600]:
a = np.array([
    [1, 1, 0],
    [1, 1, 0],
    [2, 2, 4]
])
b = np.unique(a, axis=1)
b

array([[0, 1],
       [0, 1],
       [4, 2]])

In [465]:
np.column_stack(([1, 2, 3], [4, 5, 6]))

array([[1, 4],
       [2, 5],
       [3, 6]])