### Работа с полиномами

In [274]:
import numpy as np
np.poly([-1, 1, 1, 10])
# np.poly([10, 2, 5])

array([  1., -11.,   9.,  11., -10.])

In [276]:
# np.roots([-1, -11, 9, 11, -10])
np.roots([-10, 11, 9, -11, 1])

array([-1.        ,  0.99999998,  1.00000002,  0.1       ])

In [277]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [397]:
np.poly([1, 2, 3])  # x^3 - 6x^2 + 11x - 6

array([ 1., -6., 11., -6.])

In [400]:
np.roots([1, -6, 11, -6])  # 1 2 3 в обратном порядке

array([3., 2., 1.])

In [278]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [279]:
np.polyder([1./4., 1./3., 1./2., 1., 0.])

array([1., 1., 1., 1.])

In [283]:
from numpy.polynomial import polynomial as poly
c1 = (1,2,3)
c2 = (3,2,1)
poly_sum = poly.polyadd(c1, c2)
poly_sum

array([4., 4., 4.])

In [284]:
poly.polysub(c1, c2)

array([-2.,  0.,  2.])

In [285]:
poly.polysub(c2, c1)

array([ 2.,  0., -2.])

In [286]:
poly.polymul(c1, c2)

array([ 3.,  8., 14.,  8.,  3.])

In [290]:
print(
 poly.polydiv(c1, c2),
 poly.polydiv(c2, c1)
)

(array([3.]), array([-8., -4.])) (array([0.33333333]), array([2.66666667, 1.33333333]))


### Random

In [373]:
from random import randrange
from random import randint
from random import choice
print(
 randrange(10),
 randrange(10, 20),
 randrange(0, 100, 7),
 randint(0, 200),
 choice('Python is awesome!')
)

1 11 70 10 y


In [375]:
from random import shuffle
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
shuffle(l)
l

[2, 3, 9, 4, 6, 5, 8, 1, 7]

In [379]:
from random import random as ran_random
ran_random()

0.9170911974729831

In [385]:
np.random.rand(2, 3)

array([[0.64440638, 0.06781993, 0.00765839],
       [0.25603238, 0.46950791, 0.57464085]])

In [396]:
r_matrix = np.random.randint(0, 23, (2, 3))
r_matrix

array([[ 3, 14,  5],
       [ 9, 15,  2]])

In [409]:
np.random.choice([1, 2, 3, 4, 5], (2, 3))

array([[4, 5, 3],
       [4, 3, 1]])

In [436]:
# arr = np.arange(10)
arr = np.random.randint(0, 100, (2, 3))
np.random.shuffle(arr)
arr

array([[ 7, 39,  2],
       [70, 11,  4]])

### Модуль numpy.linalg

In [446]:
A = np.random.randint(1, 5, (3, 3))
np.linalg.det(A)  # детерминант

-19.999999999999996

In [439]:
A = [[1,-1, 2],[2,-4, 2],[1, 1, -2]]
np.linalg.inv(A)  # обратная матрица

array([[ 5.00000000e-01,  1.11022302e-16,  5.00000000e-01],
       [ 5.00000000e-01, -3.33333333e-01,  1.66666667e-01],
       [ 5.00000000e-01, -1.66666667e-01, -1.66666667e-01]])

In [452]:
A = np.array([
 [1,-1, 2],
 [2,-2, 4]
])
A

array([[ 1, -1,  2],
       [ 2, -2,  4]])

In [458]:
# ранг матрицы равен 1 потому что:
# методом элементарных преобразований: умножаем 1ю строку на -2 и складываем со второй
# [1, -1,  2]
# [0,  0,  0]
# Количество ненулевых строк и есть ранг матрицы
np.linalg.matrix_rank(A)  # 1

1

In [460]:
# опять метод элементарных преобразований: умножаем 1ю строку на -2 и складываем со второй, чтобы под главной диагональю были только нули
# [1, -1,  2]
# [0, -2, -2]
# Количество ненулевых строк = 2
A = [[1, -1, 2], [2, -4, 2]]
np.linalg.matrix_rank(A)  # 2

2

### Функции модуля linalg
#### Задание:
найти решение систему линейных уравнений
\begin{cases}
x_0 + 2x_1 = 1\\
3x_0 + 5x_1 = 2\\
\end{cases}

In [259]:
a = np.array([
 [1, 2],
 [3, 5],
])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x

array([-1.,  1.])

### Задание
методом наименьших квадратов найти линейную функцию $y = mx + c$, которая наилучшим образом приближает следующие эмпирические (опытные) данные

---- |
$x_{i}$ | 1 | 2 | 3 | 4 | 5
$y_{i}$ | 5,3 | 6,3 | 4,8 | 3,8 | 3,3

In [260]:
x = np.array([1, 2, 3, 4, 5]) #[1 2 3 4 5]
y = np.array([5.3, 6.3, 4.8, 3.8, 3.3]) #[5.3 6.3 4.8 3.8 3.3]
A = np.column_stack((x, np.ones_like(x)))
A

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1]])

In [261]:
np.vstack([x, np.ones(len(x))]).T #[[1. 1.]

array([[1., 1.],
       [2., 1.],
       [3., 1.],
       [4., 1.],
       [5., 1.]])

In [262]:
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
m, c

(-0.6499999999999999, 6.6499999999999995)

### Фурье

In [263]:
def dft_slow(x):
 """Вычисление дискретное преобразование Фурье одномерного массива x"""
 x = np.asarray(x, dtype=float)
 N = x.shape[0]
 n = np.arange(N)
 k = n.reshape((N, 1))
 M = np.exp(-2j * np.pi * k * n / N)

 return np.dot(M, x)


In [264]:
x = np.random.random(8)
x

array([0.95417612, 0.26300208, 0.77321423, 0.86783801, 0.60718081,
       0.79959712, 0.31518259, 0.35615442])

In [265]:
np.allclose(dft_slow(x), np.fft.fft(x))

True

In [266]:
dft_slow(x)

array([ 4.93634538+0.00000000e+00j, -0.39424963-4.40416571e-01j,
        0.47296011+1.61393225e-01j,  1.08824023+4.75646697e-01j,
        0.36316212-4.27565273e-16j,  1.08824023-4.75646697e-01j,
        0.47296011-1.61393225e-01j, -0.39424963+4.40416571e-01j])

In [267]:
np.fft.fft(x)

array([ 4.93634538+0.j        , -0.39424963-0.44041657j,
        0.47296011+0.16139322j,  1.08824023+0.4756467j ,
        0.36316212+0.j        ,  1.08824023-0.4756467j ,
        0.47296011-0.16139322j, -0.39424963+0.44041657j])

In [462]:
%timeit dft_slow(x)

21.8 µs ± 2.96 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [463]:
%timeit np.fft.fft(x)

3.31 µs ± 47.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
