In [1]:
import pandas as pd
from pandas import Series, DataFrame
obj = Series([-4, 17, -5, 3])
obj

0    -4
1    17
2    -5
3     3
dtype: int64

In [2]:
obj.values

array([-4, 17, -5,  3])

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
obj2 = Series([50, 17, 70, 1], index=['test1', 'test2', 'test3', 'is_passed'])
obj2

test1        50
test2        17
test3        70
is_passed     1
dtype: int64

In [21]:
obj2.index

Index(['test1', 'test2', 'test3', 'is_passed'], dtype='object')

In [20]:
obj2['test2']

17

In [19]:
obj2[['test1', 'test2']]

test1    50
test2    17
dtype: int64

In [18]:
obj2[obj2 >= 50]

test1    50
test3    70
dtype: int64

In [17]:
obj2 * 2

test1        100
test2         34
test3        140
is_passed      2
dtype: int64

In [16]:
import numpy as np
np.exp(obj2)

test1        5.184706e+21
test2        2.415495e+07
test3        2.515439e+30
is_passed    2.718282e+00
dtype: float64

In [23]:
'test1' in obj2

True

In [24]:
'test11' in obj2

False

In [27]:
sdata = {'Python': 200000, 'PHP': 300000}
obj3 = pd.Series(sdata)
obj3

Python    200000
PHP       300000
dtype: int64

In [29]:
obj4 = pd.Series(sdata, index=['PHP', 'Python', 'Golang'])
obj4

PHP       300000.0
Python    200000.0
Golang         NaN
dtype: float64

In [30]:
pd.isnull(obj4)

PHP       False
Python    False
Golang     True
dtype: bool

In [31]:
pd.notnull(obj4)

PHP        True
Python     True
Golang    False
dtype: bool

In [32]:
obj4.isnull()

PHP       False
Python    False
Golang     True
dtype: bool

In [33]:
obj3

Python    200000
PHP       300000
dtype: int64

In [34]:
obj4

PHP       300000.0
Python    200000.0
Golang         NaN
dtype: float64

In [36]:
obj3 + obj4

Golang         NaN
PHP       600000.0
Python    400000.0
dtype: float64

In [40]:
obj4.name = 'language'
obj4.index.name = 'salary'
obj4

salary
PHP       300000.0
Python    200000.0
Golang         NaN
Name: language, dtype: float64

In [41]:
obj

0    -4
1    17
2    -5
3     3
dtype: int64

In [43]:
obj.index = ['t1', 't2', 't3', 't4']
obj

t1    -4
t2    17
t3    -5
t4     3
dtype: int64

### Объект DataFrame

In [83]:
data = {
    'language': ['PHP', 'PHP', 'PHP', 'Python', 'Python', 'Python'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data, index=data['year'])
frame

language  year  pop
2000      PHP  2000  1.5
2001      PHP  2001  1.7
2002      PHP  2002  3.6
2001   Python  2001  2.4
2002   Python  2002  2.9
2003   Python  2003  3.2

In [84]:
frame.head()

language  year  pop
2000      PHP  2000  1.5
2001      PHP  2001  1.7
2002      PHP  2002  3.6
2001   Python  2001  2.4
2002   Python  2002  2.9

In [85]:
pd.DataFrame(data, columns=['year', 'language', 'pop'])

year language  pop
0  2000      PHP  1.5
1  2001      PHP  1.7
2  2002      PHP  3.6
3  2001   Python  2.4
4  2002   Python  2.9
5  2003   Python  3.2

In [86]:
frame2 = pd.DataFrame(
    data,
    columns=['year', 'language', 'pop', 'debt'],
    index=['one', 'two', 'three', 'four', 'five', 'six']
)
frame2

year language  pop debt
one    2000      PHP  1.5  NaN
two    2001      PHP  1.7  NaN
three  2002      PHP  3.6  NaN
four   2001   Python  2.4  NaN
five   2002   Python  2.9  NaN
six    2003   Python  3.2  NaN

In [87]:
frame2.columns

Index(['year', 'language', 'pop', 'debt'], dtype='object')

In [89]:
frame2['language']

one         PHP
two         PHP
three       PHP
four     Python
five     Python
six      Python
Name: language, dtype: object

In [90]:
frame2.loc['three']

year        2002
language     PHP
pop          3.6
debt         NaN
Name: three, dtype: object

In [91]:
frame2['debt'] = 16.5
frame2

year language  pop  debt
one    2000      PHP  1.5  16.5
two    2001      PHP  1.7  16.5
three  2002      PHP  3.6  16.5
four   2001   Python  2.4  16.5
five   2002   Python  2.9  16.5
six    2003   Python  3.2  16.5

In [92]:
frame2['debt'] = np.random.randint(0, 10, len(frame2.index))
frame2

year language  pop  debt
one    2000      PHP  1.5     0
two    2001      PHP  1.7     3
three  2002      PHP  3.6     4
four   2001   Python  2.4     3
five   2002   Python  2.9     6
six    2003   Python  3.2     9

In [93]:
frame2['debt'] = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2

year language  pop  debt
one    2000      PHP  1.5   NaN
two    2001      PHP  1.7  -1.2
three  2002      PHP  3.6   NaN
four   2001   Python  2.4  -1.5
five   2002   Python  2.9  -1.7
six    2003   Python  3.2   NaN

In [96]:
frame2['is_popular'] = frame2['pop'] > 2
frame2

year language  pop  debt  is_popular
one    2000      PHP  1.5   NaN       False
two    2001      PHP  1.7  -1.2       False
three  2002      PHP  3.6   NaN        True
four   2001   Python  2.4  -1.5        True
five   2002   Python  2.9  -1.7        True
six    2003   Python  3.2   NaN        True

In [97]:
del frame2['is_popular']
frame2.columns

Index(['year', 'language', 'pop', 'debt'], dtype='object')

In [102]:
pop = {
    'Python':   {2001: 2.4, 2002: 2.9},
    'PHP':     {2000: 1.5, 2001: 1.7, 2002: 3.6},
}
frame3 = DataFrame(pop)
frame3

Python  PHP
2001     2.4  1.7
2002     2.9  3.6
2000     NaN  1.5

In [103]:
frame3.T

2001  2002  2000
Python   2.4   2.9   NaN
PHP      1.7   3.6   1.5

In [104]:
DataFrame(pop, index=[2001, 2002, 2003])

Python  PHP
2001     2.4  1.7
2002     2.9  3.6
2003     NaN  NaN

In [106]:
# Словари объектов Series интерпретируются очень похоже:
pdata = {
    'PHP': frame3['PHP'][:-1],
    'Python':frame3['Python'][:2]
}
DataFrame(pdata)

PHP  Python
2001  1.7     2.4
2002  3.6     2.9

In [107]:
# Если у объектов, возвращаемых при обращении к атрибутам index и columns объекта DataFrame, установлен атрибут name, то он также выводится:
frame3.index.name = 'year'
frame3.columns.name = 'language'
frame3

language  Python  PHP
year                 
2001         2.4  1.7
2002         2.9  3.6
2000         NaN  1.5

In [108]:
# Как и в случае Series, атрибут values возвращает данные, хранящиеся в DataFrame, в виде двумерного массива ndarray:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [109]:
frame2.values

array([[2000, 'PHP', 1.5, nan],
       [2001, 'PHP', 1.7, -1.2],
       [2002, 'PHP', 3.6, nan],
       [2001, 'Python', 2.4, -1.5],
       [2002, 'Python', 2.9, -1.7],
       [2003, 'Python', 3.2, nan]], dtype=object)

### Индексные объекты
В индексных объектах pandas хранятся метки вдоль осей и прочие метаданные (например, имена осей). Любой массив или иная последовательность меток, указанная при конструировании Series или DataFrame, преобразуется в объект Index

In [110]:
obj = Series(np.random.randint(0, 10, 3), index=['PHP', 'Python', 'Golang'])
index = obj.index
index

Index(['PHP', 'Python', 'Golang'], dtype='object')

In [111]:
# срез индекса начиная с первого (не нулевого)
index[1:]

Index(['Python', 'Golang'], dtype='object')

In [113]:
# Индексные объекты неизменяемы, т.е. пользователь не может их модифицировать:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [114]:
# Неизменяемость важна, для того чтобы несколько структур данных могли совместно использовать один и тот же индексный объект, не опасаясь его повредить:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [116]:
# присвоим тот же индекс дата фрейму
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [118]:
# созданный индекс и индекс дата-фрейма это один и тот же объект в памяти
obj2.index is labels

True

In [119]:
# Индексный объект не только похож на массив, но и ведет себя как множество фиксированного размера:
frame3

language  Python  PHP
year                 
2001         2.4  1.7
2002         2.9  3.6
2000         NaN  1.5

In [120]:
frame3.columns

Index(['Python', 'PHP'], dtype='object', name='language')

In [121]:
'PHP' in frame3.columns

True

In [122]:
2003 in frame2.index

False

In [138]:
# В отличие от множеств Python, индекс в pandas может содержать повторяющиеся метки:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [139]:
# добавление
dup_labels = dup_labels.append(pd.Index(['test']))

In [140]:
# разница
dup_labels.difference(['bar'])

Index(['foo', 'test'], dtype='object')

In [141]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar', 'test'], dtype='object')

In [142]:
# в каких находится 'test'
dup_labels.isin(['test'])

array([False, False, False, False,  True])

In [147]:
dup_labels.delete(4) # возвращает новый с удаленным по номеру (индексу) элемент

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [148]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar', 'test'], dtype='object')

In [153]:
dup_labels2 = dup_labels.drop('test') # возвращает новый с удаленным элементом

In [154]:
dup_labels2

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [157]:
dup_labels2.is_monotonic  # восходящая ли последовательность

False

In [158]:
pd.Index([2, 3, 4, 5]).is_monotonic

True

In [159]:
pd.Index([2, 3, 4, 5]).is_unique

True

In [160]:
pd.Index([2, 3, 4, 5]).unique()

Int64Index([2, 3, 4, 5], dtype='int64')